## conda install -c conda-forge faker 
 
0. Fake data generation like name, address, email, text, sentence, etc
1. Creating a JSON file of fake data.
2. Different language fake data printed.
3. Creating Profile
4. Seeding i.e printing particular fake data
5. Generating sentence that contains words we provided.

In [16]:
from faker import Faker
fake = Faker()

In [44]:
print(fake.email()) 
print(fake.country()) 
print(fake.name()) 
print(fake.text()) 
print(fake.latitude())
print(fake.longitude()) 
print(fake.url()) 
print(fake.date()) 
print(fake.time())

sallen@berger.com
Nauru
Daniel Reynolds MD
Everyone her nice where more. Again physical paper structure deal expect my event.
63.700313
-12.898146
http://morris.com/
2006-09-13
05:01:17

### Application 1 : Create a json of 100 students with name students.json that contains student name, address, location coordinates and student roll number.

In [20]:
from faker import Faker 
import json                     # To create a json file                 
from random import randint      # For student id 
fake = Faker() 

def input_data(x): 
  
    # dictionary 
    student_data ={} 
    for i in range(0, x): 
        student_data[i]={} 
        student_data[i]['id']= randint(1, 100) 
        student_data[i]['name']= fake.name() 
        student_data[i]['address']= fake.address() 
        student_data[i]['latitude']= str(fake.latitude()) 
        student_data[i]['longitude']= str(fake.longitude()) 
    print(student_data) 
  
    # dictionary dumped as json in a json file 
    with open('students.json', 'w') as fp: 
        json.dump(student_data, fp) 
      
  
def main():                  # Enter number of students 
    number_of_students = 10  # For the above task make this 100 
    input_data(number_of_students) 
main() 

# The folder or location where this python code is save there a students.json will be created having 10 students data.

{0: {'id': 82, 'name': 'Richard Green', 'address': '2909 Laura Pines\nMillershire, WV 47288', 'latitude': '50.8922865', 'longitude': '0.972732'}, 1: {'id': 10, 'name': 'Caitlyn Welch', 'address': '137 Paul Circles\nNataliebury, KS 66583', 'latitude': '70.2127435', 'longitude': '-42.423357'}, 2: {'id': 90, 'name': 'Timothy Rosales', 'address': '81869 Heather Rapid Apt. 128\nRandybury, WA 76116', 'latitude': '1.4779455', 'longitude': '-133.846608'}, 3: {'id': 70, 'name': 'William Chang', 'address': '949 Alvarez Square\nNorth Nancymouth, ID 25149', 'latitude': '6.3144745', 'longitude': '-84.859375'}, 4: {'id': 13, 'name': 'Larry Taylor', 'address': '6361 Zachary Terrace\nSouth Markburgh, NC 15123', 'latitude': '-68.717990', 'longitude': '93.838421'}, 5: {'id': 67, 'name': 'James Velazquez', 'address': '1487 Blake Centers Apt. 395\nBairdland, WA 45922', 'latitude': '9.565911', 'longitude': '40.276840'}, 6: {'id': 17, 'name': 'Carrie Fitzgerald', 'address': '7405 Kristen Club\nNorth Jason, CA 44050', 'latitude': '-22.132195', 'longitude': '144.222634'}, 7: {'id': 58, 'name': 'David Thomas', 'address': '446 Charles River\nTaraborough, AR 57963', 'latitude': '48.699360', 'longitude': '108.290951'}, 8: {'id': 49, 'name': 'Patricia Prince', 'address': '73771 Harris Valleys\nCollinston, UT 68714', 'latitude': '-23.881745', 'longitude': '120.408931'}, 9: {'id': 43, 'name': 'Tara Huber', 'address': '5391 Moore Vista Apt. 643\nWest Kathleenmouth, WV 31385', 'latitude': '70.6573665', 'longitude': '-166.009254'}}

### Application 2: Print 10 fake names and countries in Hindi language.

In [21]:
from faker import Faker 
fake = Faker('hi_IN')      #'hi_IN' changed the language 
for i in range(0, 10): 
    print('Name->', fake.name(), 'Country->', fake.country())

Name-> कुलकर्णी, आन्वी Country-> बुरूंडी
Name-> मल्लिक, मोहन Country-> किरिबाती
Name-> अनन्या लाल Country-> लातविया
Name-> गौतम अब्बासी Country-> यूनान
Name-> हासन गांगुली Country-> बुल्गारिया
Name-> इन्द्रजित ड़ाल Country-> बेल्जियम
Name-> आनन्द कुमार Country-> उरूग्वे
Name-> गौतम कृष्णा Country-> ओमान
Name-> हनुमान् गणेश Country-> वेटिकन सिटी
Name-> फ़ातिमा माने Country-> घाना

### Application 3: Create fake profile

In [23]:
from faker import Faker 
fake = Faker() 
print(fake.profile())

{'job': 'Metallurgist', 'company': 'Patrick, Gonzalez and Stevens', 'ssn': '757-33-5469', 'residence': '116 Gonzalez Radial\nWest Vickie, LA 58004', 'current_location': (Decimal('-44.329086'), Decimal('-62.423617')), 'blood_group': 'A-', 'website': ['https://www.jordan.com/'], 'username': 'brianmathews', 'name': 'Rodney Smith', 'sex': 'M', 'address': '099 Steven Vista Suite 123\nEast Alexander, AZ 37676', 'mail': 'richardrobertson@gmail.com', 'birthdate': datetime.date(1931, 4, 23)}

### Application 4: Seeding the Generator getting particular fake data again.
    NOTE: Even if I run the program, again and again, I would get the same result. As soon as I remove that fake.seed(1) line, we see randomness in data generation.

In [34]:
from faker import Faker 
fake = Faker()   
Faker.seed(1) 

print(fake.name()) 
print(fake.address()) 
print(fake.email())

Ryan Gallagher
6317 Mary Light
Smithview, HI 13900
johnsonamber@hotmail.com

### Application 5: Print data from the list you want.

In [38]:
from faker import Faker 
fake = Faker() 

# Print random sentences 
print(fake.sentence()) 
print()  
# List has words that we want in our sentence 
word_list = ["GFG", "Geeksforgeeks", "shaurya", "says", "Gfg", "GEEKS"] 
  
# Let's print 5 sentences that have words from our word_list  
for i in range(0, 5): 
  
    # You need to use ext_word_list = listnameyoucreated  
    print(fake.sentence(ext_word_list = word_list))

Light final summer.

Says shaurya Geeksforgeeks says GEEKS Gfg says GEEKS.
Shaurya shaurya GEEKS shaurya GEEKS.
Says Gfg shaurya GEEKS GEEKS GEEKS says.
Says says shaurya GFG.
Says Geeksforgeeks says shaurya shaurya shaurya.

### Challeng: Create 500 random Users for MySQL Exercise
https://faker.readthedocs.io/en/master/providers/faker.providers.date_time.html

https://programmer.help/blogs/python-s-forged-data-generator-faker.html

from faker import Faker 
import json                     # To create a json file                 
from random import randint      # For student id 
fake = Faker() 

def input_data(x): 
  
    # dictionary 
    student_data ={} 
    for i in range(0, x): 
        student_data[i]={} 
        student_data[i]['id']= randint(1, 100) 
        student_data[i]['name']= fake.name() 
        student_data[i]['address']= fake.address() 
        student_data[i]['latitude']= str(fake.latitude()) 
        student_data[i]['longitude']= str(fake.longitude()) 
    print(student_data) 
  
    # dictionary dumped as json in a json file 
    with open('students.json', 'w') as fp: 
        json.dump(student_data, fp) 
      
  
def main():                  # Enter number of students 
    number_of_students = 10  # For the above task make this 100 
    input_data(number_of_students) 
main() 

The folder or location where this python code is save there a students.json will be created having 10 students data.

In [121]:
from faker import Faker 
import json                     # To create a json file                 
from random import randint      # For user_id
fake = Faker() 

def input_data(x): 
  
    # dictionary 
    user_data ={} 
    for i in range(1, x): 
        user_data[i]={} 
        user_data[i]['name']= fake.name() 
        user_data[i]['email']= fake.email() 
        user_data[i]['registered']= fake.date()
        user_data[i]['timestamp']=fake.time()
    print(user_data) 
  
    #dictionary dumped as json in a json file 
    with open('users.json', 'w') as fp: 
        json.dump(user_data, fp) 
      
def main():                  # Enter number of users 
    number_of_users = 501    # For the above task make this 100 
    input_data(number_of_users) 
main() 

# The folder or location where this python code is save there a users.json will be created having 10 users data.

{1: {'name': 'Donald Cooper', 'email': 'byrdjeffrey@wright.net', 'registered': '1990-01-15', 'timestamp': '22:34:17'}, 2: {'name': 'Ryan Howell', 'email': 'bryanchavez@smith.com', 'registered': '2008-01-06', 'timestamp': '15:39:05'}, 3: {'name': 'Michaela Adams', 'email': 'nparker@gmail.com', 'registered': '2003-07-01', 'timestamp': '11:26:07'}, 4: {'name': 'Jerry Rivera', 'email': 'johnathan39@yahoo.com', 'registered': '1976-04-27', 'timestamp': '13:21:36'}, 5: {'name': 'Emily Manning', 'email': 'annasmith@baker-foster.com', 'registered': '1985-08-10', 'timestamp': '04:35:15'}, 6: {'name': 'Todd Guzman', 'email': 'jim25@anderson.biz', 'registered': '1979-07-23', 'timestamp': '07:58:39'}, 7: {'name': 'Joseph Lamb', 'email': 'tannerhenderson@yahoo.com', 'registered': '1984-10-13', 'timestamp': '10:10:08'}, 8: {'name': 'Mary Martin', 'email': 'kathleen24@austin.com', 'registered': '1971-06-13', 'timestamp': '12:21:38'}, 9: {'name': 'Angela Hale', 'email': 'yhill@vazquez.org', 'registered': '2004-08-28', 'timestamp': '05:58:00'}, 10: {'name': 'Michelle Thompson', 'email': 'malonejennifer@herrera.org', 'registered': '1978-11-21', 'timestamp': '15:24:52'}, 11: {'name': 'Dr. David Kelly', 'email': 'jacquelineoconnor@hotmail.com', 'registered': '2013-06-04', 'timestamp': '17:05:57'}, 12: {'name': 'Jeanette Schmidt', 'email': 'thomasrobert@evans-hunter.net', 'registered': '1970-01-26', 'timestamp': '06:29:32'}, 13: {'name': 'Donna Rollins', 'email': 'adaniels@yahoo.com', 'registered': '2009-04-17', 'timestamp': '04:45:03'}, 14: {'name': 'Robert Howard', 'email': 'jennifer00@smith.com', 'registered': '2009-04-22', 'timestamp': '13:29:35'}, 15: {'name': 'Sarah Levine', 'email': 'xboyd@hotmail.com', 'registered': '1981-02-15', 'timestamp': '17:49:26'}, 16: {'name': 'Brittany Mcdonald', 'email': 'ianderson@miller.org', 'registered': '1992-11-23', 'timestamp': '21:25:58'}, 17: {'name': 'John Odonnell', 'email': 'kmoody@hotmail.com', 'registered': '2016-12-08', 'timestamp': '22:50:41'}, 18: {'name': 'Zachary Rangel', 'email': 'zwise@martin.net', 'registered': '1970-09-12', 'timestamp': '21:00:44'}, 19: {'name': 'Benjamin Duffy', 'email': 'xbrewer@king.com', 'registered': '2014-02-16', 'timestamp': '05:21:41'}, 20: {'name': 'Shannon Webster', 'email': 'brandonodonnell@smith.biz', 'registered': '2014-06-08', 'timestamp': '19:27:27'}, 21: {'name': 'James Osborne', 'email': 'rramirez@yahoo.com', 'registered': '1984-03-10', 'timestamp': '14:58:28'}, 22: {'name': 'Kayla Finley', 'email': 'cmiles@king.com', 'registered': '1978-07-21', 'timestamp': '07:02:59'}, 23: {'name': 'Christine Holmes', 'email': 'tbenjamin@harrell-schwartz.com', 'registered': '2017-08-08', 'timestamp': '11:34:32'}, 24: {'name': 'Tim Tucker', 'email': 'michaellewis@gmail.com', 'registered': '1981-12-31', 'timestamp': '10:14:44'}, 25: {'name': 'Steven Walker', 'email': 'juan37@morrow-white.info', 'registered': '2017-05-15', 'timestamp': '10:44:57'}, 26: {'name': 'Regina Wagner', 'email': 'ortizedward@flores.biz', 'registered': '1975-09-06', 'timestamp': '11:09:48'}, 27: {'name': 'Derek Thompson Jr.', 'email': 'travis99@perez.net', 'registered': '2007-03-06', 'timestamp': '02:05:31'}, 28: {'name': 'Andre Hamilton', 'email': 'williamslori@hotmail.com', 'registered': '1976-05-13', 'timestamp': '15:49:22'}, 29: {'name': 'Melissa James', 'email': 'donald19@hotmail.com', 'registered': '2009-01-14', 'timestamp': '10:23:32'}, 30: {'name': 'Charles Obrien', 'email': 'joseph54@hotmail.com', 'registered': '1982-01-28', 'timestamp': '15:27:06'}, 31: {'name': 'Kim Browning', 'email': 'john85@skinner-stephens.com', 'registered': '2011-03-17', 'timestamp': '10:59:40'}, 32: {'name': 'Stacy Strickland', 'email': 'yroberts@yahoo.com', 'registered': '2007-09-22', 'timestamp': '13:16:59'}, 33: {'name': 'Andrew Lewis', 'email': 'tsmith@mckee.biz', 'registered': '2019-01-29', 'timestamp': '20:18:32'}, 34: {'name': 'Michael Cochran', 'email': 'perezcarolyn@yahoo.com', 'registered': '1972-07-23', 'timestamp': '10:04:20'}, 35: {'name': 'Tanya Francis', 'email': 'christophermercado@lee.com', 'registered': '2007-04-04', 'timestamp': '16:33:27'}, 36: {'name': 'Melissa Richardson', 'email': 'lsandoval@porter.com', 'registered': '1985-07-04', 'timestamp': '13:40:35'}, 37: {'name': 'Patricia Combs', 'email': 'mwhite@parker.biz', 'registered': '1984-07-02', 'timestamp': '22:47:09'}, 38: {'name': 'Christopher Harmon', 'email': 'dmcclure@hotmail.com', 'registered': '1974-01-19', 'timestamp': '05:47:35'}, 39: {'name': 'Dana Sloan', 'email': 'youngmaria@rodriguez-durham.com', 'registered': '2005-01-25', 'timestamp': '03:03:59'}, 40: {'name': 'Steven Williams', 'email': 'kenneth46@johnson-reynolds.com', 'registered': '1978-05-29', 'timestamp': '17:09:49'}, 41: {'name': 'Christopher Welch', 'email': 'esmith@hotmail.com', 'registered': '1972-12-11', 'timestamp': '02:37:15'}, 42: {'name': 'Austin Lawson', 'email': 'melaniesaunders@yahoo.com', 'registered': '1994-09-06', 'timestamp': '12:16:02'}, 43: {'name': 'Katherine Moreno', 'email': 'jessicaholmes@yahoo.com', 'registered': '2011-03-31', 'timestamp': '09:26:10'}, 44: {'name': 'Matthew Robles', 'email': 'mary31@gmail.com', 'registered': '1999-07-20', 'timestamp': '06:38:01'}, 45: {'name': 'Tracy Powers', 'email': 'hermansamantha@rogers-dean.net', 'registered': '2008-07-09', 'timestamp': '22:18:14'}, 46: {'name': 'Melissa Daniel', 'email': 'christineandrews@hotmail.com', 'registered': '1971-03-31', 'timestamp': '14:04:21'}, 47: {'name': 'Gabriel Obrien', 'email': 'calvinwilson@hernandez.com', 'registered': '1988-07-14', 'timestamp': '07:41:29'}, 48: {'name': 'Laura Cole', 'email': 'terryduane@hotmail.com', 'registered': '2013-04-05', 'timestamp': '06:42:15'}, 49: {'name': 'Joseph Stevens', 'email': 'yschmidt@castillo.org', 'registered': '1971-11-30', 'timestamp': '14:48:27'}, 50: {'name': 'Matthew Gomez', 'email': 'williamsrebecca@yahoo.com', 'registered': '2011-12-21', 'timestamp': '18:48:09'}, 51: {'name': 'James Norris', 'email': 'lauren80@mayer.com', 'registered': '2004-01-12', 'timestamp': '09:37:46'}, 52: {'name': 'William Lyons', 'email': 'harrisonstephanie@barber.com', 'registered': '2013-01-18', 'timestamp': '07:09:50'}, 53: {'name': 'Maria Anderson', 'email': 'ochoarobert@nunez-shaw.com', 'registered': '1970-07-25', 'timestamp': '20:14:25'}, 54: {'name': 'Melissa Richardson', 'email': 'evansmichael@smith-moore.com', 'registered': '2005-01-25', 'timestamp': '19:12:04'}, 55: {'name': 'Dustin Ball', 'email': 'olivia49@yahoo.com', 'registered': '2016-06-07', 'timestamp': '14:05:02'}, 56: {'name': 'Abigail Cruz', 'email': 'dvega@gmail.com', 'registered': '1982-01-22', 'timestamp': '00:44:29'}, 57: {'name': 'Andrew Nelson', 'email': 'ostein@gmail.com', 'registered': '2018-10-15', 'timestamp': '05:13:29'}, 58: {'name': 'Amanda Coleman', 'email': 'wernertom@munoz-sutton.com', 'registered': '1979-03-29', 'timestamp': '10:16:53'}, 59: {'name': 'Robert Watson', 'email': 'jason52@michael.org', 'registered': '1977-12-15', 'timestamp': '09:55:42'}, 60: {'name': 'Jonathan Martinez', 'email': 'jenkinsanthony@gmail.com', 'registered': '1993-05-13', 'timestamp': '02:04:22'}, 61: {'name': 'Danielle Williams', 'email': 'hsimon@garcia.com', 'registered': '2018-04-01', 'timestamp': '09:27:42'}, 62: {'name': 'Kyle Humphrey', 'email': 'johnsonholly@gmail.com', 'registered': '1982-10-28', 'timestamp': '20:18:05'}, 63: {'name': 'Raymond Simon', 'email': 'patelkatherine@hotmail.com', 'registered': '2003-01-07', 'timestamp': '22:23:14'}, 64: {'name': 'Carly Howell', 'email': 'jeffrey31@spencer-martin.org', 'registered': '1978-12-04', 'timestamp': '01:32:17'}, 65: {'name': 'Jeffrey Nolan', 'email': 'derekperry@bennett.org', 'registered': '2011-10-23', 'timestamp': '22:21:45'}, 66: {'name': 'Jodi Pratt', 'email': 'michaelholden@yahoo.com', 'registered': '1980-12-09', 'timestamp': '05:17:04'}, 67: {'name': 'Angela Shaw', 'email': 'sarahjennings@davis-mcdonald.org', 'registered': '2007-02-11', 'timestamp': '05:04:01'}, 68: {'name': 'Fred Lopez', 'email': 'belljames@wright.com', 'registered': '1986-10-03', 'timestamp': '18:27:56'}, 69: {'name': 'Mrs. Audrey Smith', 'email': 'robertpowell@hotmail.com', 'registered': '2010-06-17', 'timestamp': '18:57:46'}, 70: {'name': 'Michael Cortez', 'email': 'hwaters@hotmail.com', 'registered': '2011-03-22', 'timestamp': '04:49:13'}, 71: {'name': 'Diane Martinez', 'email': 'wangronald@yahoo.com', 'registered': '1994-10-03', 'timestamp': '07:15:59'}, 72: {'name': 'James Adams DVM', 'email': 'patricia44@ortega.info', 'registered': '2003-03-26', 'timestamp': '17:51:33'}, 73: {'name': 'Judy Richardson', 'email': 'balljohn@smith.com', 'registered': '2017-09-15', 'timestamp': '13:55:01'}, 74: {'name': 'Mrs. Kayla Jennings DVM', 'email': 'zgallagher@armstrong-johnson.biz', 'registered': '2019-02-24', 'timestamp': '15:22:39'}, 75: {'name': 'Brian Phillips', 'email': 'johnny65@hotmail.com', 'registered': '1993-11-17', 'timestamp': '00:23:09'}, 76: {'name': 'Ricky Camacho DDS', 'email': 'markbauer@yahoo.com', 'registered': '2017-04-07', 'timestamp': '15:49:51'}, 77: {'name': 'Cindy Morales', 'email': 'dalton44@aguilar.com', 'registered': '1979-10-26', 'timestamp': '04:49:15'}, 78: {'name': 'Ryan Gilbert', 'email': 'markkelley@hotmail.com', 'registered': '2018-09-21', 'timestamp': '23:14:12'}, 79: {'name': 'Monica Clark', 'email': 'isanchez@yahoo.com', 'registered': '1991-04-04', 'timestamp': '13:30:32'}, 80: {'name': 'Sandra Lambert', 'email': 'holmesjeffrey@barr.com', 'registered': '1977-03-01', 'timestamp': '13:33:01'}, 81: {'name': 'Timothy Barnes', 'email': 'nathanmiller@rodriguez.com', 'registered': '2005-11-11', 'timestamp': '00:00:37'}, 82: {'name': 'Nicholas Koch', 'email': 'davidtran@jones.com', 'registered': '2009-05-16', 'timestamp': '09:47:39'}, 83: {'name': 'Mary Simon', 'email': 'jameswilson@yahoo.com', 'registered': '1989-02-12', 'timestamp': '20:13:56'}, 84: {'name': 'Valerie Tran', 'email': 'santosalejandra@gmail.com', 'registered': '2018-11-11', 'timestamp': '16:14:09'}, 85: {'name': 'Christopher Abbott', 'email': 'rothjason@hotmail.com', 'registered': '1984-03-30', 'timestamp': '21:27:35'}, 86: {'name': 'Carly Sandoval', 'email': 'coreyshaw@yahoo.com', 'registered': '2003-08-23', 'timestamp': '08:22:59'}, 87: {'name': 'Danny Peters', 'email': 'isaac42@hotmail.com', 'registered': '2012-09-29', 'timestamp': '23:19:40'}, 88: {'name': 'Kim Reyes', 'email': 'staceyrobertson@levy-smith.com', 'registered': '1976-03-30', 'timestamp': '01:23:13'}, 89: {'name': 'Carolyn White', 'email': 'powellmark@hotmail.com', 'registered': '1972-03-12', 'timestamp': '05:33:32'}, 90: {'name': 'Melissa Tran', 'email': 'debrarichard@cole.com', 'registered': '1998-12-18', 'timestamp': '08:49:47'}, 91: {'name': 'Noah Castillo', 'email': 'marcjackson@watkins-meyer.info', 'registered': '2000-01-01', 'timestamp': '03:27:39'}, 92: {'name': 'Ashley Warren', 'email': 'walvarez@white-benson.net', 'registered': '1988-12-26', 'timestamp': '10:59:48'}, 93: {'name': 'Benjamin Pacheco', 'email': 'kelleypamela@hotmail.com', 'registered': '2008-04-02', 'timestamp': '16:09:47'}, 94: {'name': 'Dr. Robert White MD', 'email': 'wcole@herman-king.com', 'registered': '1985-05-10', 'timestamp': '14:17:09'}, 95: {'name': 'Dylan Sloan', 'email': 'bowerssherry@vazquez-mccormick.com', 'registered': '2013-01-18', 'timestamp': '11:38:40'}, 96: {'name': 'Jason Bell', 'email': 'vazquezselena@yahoo.com', 'registered': '2010-07-18', 'timestamp': '20:20:11'}, 97: {'name': 'Sara Gonzalez', 'email': 'paullowe@knox-raymond.com', 'registered': '2000-07-29', 'timestamp': '17:43:01'}, 98: {'name': 'Mr. Christopher Coleman', 'email': 'brandon43@fisher.info', 'registered': '1982-09-17', 'timestamp': '15:58:20'}, 99: {'name': 'Christian Taylor', 'email': 'monroedaniel@gmail.com', 'registered': '1982-06-07', 'timestamp': '20:32:59'}, 100: {'name': 'Andrew Webb', 'email': 'pittsjerry@hotmail.com', 'registered': '2004-02-26', 'timestamp': '15:48:36'}, 101: {'name': 'Matthew Perez', 'email': 'william53@bauer-smith.com', 'registered': '1979-02-05', 'timestamp': '16:40:33'}, 102: {'name': 'Andrew Drake', 'email': 'vanessa93@mcdonald.com', 'registered': '2017-12-13', 'timestamp': '12:00:43'}, 103: {'name': 'Melissa Smith', 'email': 'joshuaestrada@johnson-martin.net', 'registered': '2003-08-07', 'timestamp': '04:50:38'}, 104: {'name': 'Stephanie Watson', 'email': 'fordteresa@miller.com', 'registered': '1985-11-17', 'timestamp': '02:19:03'}, 105: {'name': 'Nicholas Johnson', 'email': 'robertsnicholas@weaver.info', 'registered': '2007-06-17', 'timestamp': '20:00:24'}, 106: {'name': 'Nathan Cabrera', 'email': 'zbryant@gmail.com', 'registered': '2004-06-10', 'timestamp': '02:49:25'}, 107: {'name': 'Benjamin Downs', 'email': 'qrandolph@russo.info', 'registered': '2009-07-31', 'timestamp': '09:38:25'}, 108: {'name': 'Deborah Hendricks', 'email': 'robertwilson@morgan-foster.net', 'registered': '1997-03-05', 'timestamp': '15:29:16'}, 109: {'name': 'Jessica Ward', 'email': 'christopherwoods@yahoo.com', 'registered': '1980-05-04', 'timestamp': '06:16:09'}, 110: {'name': 'Vincent Davis', 'email': 'ystewart@hotmail.com', 'registered': '1970-05-10', 'timestamp': '07:42:33'}, 111: {'name': 'Jeanette Farrell', 'email': 'timothycrane@potter.info', 'registered': '1971-11-07', 'timestamp': '04:25:49'}, 112: {'name': 'Mr. Ruben Flores PhD', 'email': 'robertreynolds@baker.com', 'registered': '2016-02-25', 'timestamp': '22:11:04'}, 113: {'name': 'Tom Miller', 'email': 'dwhite@williams.com', 'registered': '2019-06-04', 'timestamp': '21:55:05'}, 114: {'name': 'Peter Erickson', 'email': 'aaguirre@neal.com', 'registered': '1978-10-21', 'timestamp': '05:05:36'}, 115: {'name': 'Lisa Crawford', 'email': 'phillipaustin@gmail.com', 'registered': '1994-06-05', 'timestamp': '03:05:24'}, 116: {'name': 'Tina Koch', 'email': 'wardrichard@gmail.com', 'registered': '2013-03-21', 'timestamp': '06:54:30'}, 117: {'name': 'Andrea Arnold', 'email': 'azuniga@yahoo.com', 'registered': '1981-12-29', 'timestamp': '00:49:17'}, 118: {'name': 'Philip Willis DDS', 'email': 'prush@gmail.com', 'registered': '1970-08-22', 'timestamp': '11:05:25'}, 119: {'name': 'Jared Sawyer', 'email': 'catherine70@gmail.com', 'registered': '2018-07-24', 'timestamp': '04:18:43'}, 120: {'name': 'Bobby Lee', 'email': 'david07@johnson.com', 'registered': '1976-04-09', 'timestamp': '02:38:53'}, 121: {'name': 'Megan Mendoza', 'email': 'james59@hotmail.com', 'registered': '1988-09-27', 'timestamp': '17:07:39'}, 122: {'name': 'Linda Riley', 'email': 'jamesgraham@king.com', 'registered': '1979-07-17', 'timestamp': '04:31:08'}, 123: {'name': 'Stephanie Thornton', 'email': 'johnallen@gmail.com', 'registered': '1972-02-11', 'timestamp': '20:10:04'}, 124: {'name': 'Michael Moore', 'email': 'hansonashley@hotmail.com', 'registered': '2014-12-21', 'timestamp': '14:39:25'}, 125: {'name': 'Thomas Wilkinson', 'email': 'abaker@hotmail.com', 'registered': '1982-08-31', 'timestamp': '07:52:14'}, 126: {'name': 'Amber Stokes', 'email': 'kimsarah@gmail.com', 'registered': '1987-12-15', 'timestamp': '08:07:56'}, 127: {'name': 'Stephen Chan', 'email': 'zgutierrez@martin.com', 'registered': '1985-06-26', 'timestamp': '08:07:01'}, 128: {'name': 'Melissa Holloway', 'email': 'campostina@gmail.com', 'registered': '2018-04-10', 'timestamp': '18:35:19'}, 129: {'name': 'Elizabeth Crawford', 'email': 'huffryan@hotmail.com', 'registered': '1973-10-03', 'timestamp': '15:25:26'}, 130: {'name': 'Lisa Smith', 'email': 'angela31@taylor.com', 'registered': '2015-09-05', 'timestamp': '01:51:29'}, 131: {'name': 'Samuel Wise', 'email': 'markgriffin@yahoo.com', 'registered': '1985-02-18', 'timestamp': '00:34:31'}, 132: {'name': 'Sheena Guerrero', 'email': 'hholland@gmail.com', 'registered': '1991-06-07', 'timestamp': '13:47:10'}, 133: {'name': 'Ian Day', 'email': 'billlee@jimenez.biz', 'registered': '1983-06-27', 'timestamp': '09:58:03'}, 134: {'name': 'Jessica Lewis', 'email': 'annaorozco@medina-reyes.com', 'registered': '2010-05-30', 'timestamp': '02:50:05'}, 135: {'name': 'John Jones', 'email': 'conradjohn@hotmail.com', 'registered': '2004-01-22', 'timestamp': '09:32:11'}, 136: {'name': 'Melanie Bailey', 'email': 'rgreer@harmon-tran.com', 'registered': '1981-01-01', 'timestamp': '12:43:24'}, 137: {'name': 'Kristin Fischer', 'email': 'john41@woodard.com', 'registered': '1975-06-17', 'timestamp': '06:54:43'}, 138: {'name': 'Dr. Tamara Wright', 'email': 'elizabeth12@woods.com', 'registered': '2011-07-12', 'timestamp': '01:52:27'}, 139: {'name': 'Jeremy Grant', 'email': 'mccarthykimberly@hotmail.com', 'registered': '2006-02-12', 'timestamp': '07:30:14'}, 140: {'name': 'Julie Fernandez', 'email': 'lblake@wilson-mccann.com', 'registered': '1991-11-03', 'timestamp': '17:47:43'}, 141: {'name': 'Jennifer Spears', 'email': 'mitchellana@johnson-woods.com', 'registered': '1995-09-28', 'timestamp': '06:30:10'}, 142: {'name': 'James Walker', 'email': 'michelle56@gmail.com', 'registered': '2009-05-04', 'timestamp': '09:01:41'}, 143: {'name': 'David Johnston', 'email': 'lewistyler@anderson.org', 'registered': '2010-11-14', 'timestamp': '04:43:55'}, 144: {'name': 'Micheal Jenkins', 'email': 'randy84@brown.com', 'registered': '1990-10-24', 'timestamp': '00:10:20'}, 145: {'name': 'Bryce Morris', 'email': 'brooke22@gmail.com', 'registered': '1995-04-10', 'timestamp': '20:21:56'}, 146: {'name': 'Tina Young', 'email': 'charles39@hotmail.com', 'registered': '1972-07-05', 'timestamp': '01:22:59'}, 147: {'name': 'Randall Warren', 'email': 'keith72@hotmail.com', 'registered': '1998-09-20', 'timestamp': '05:07:13'}, 148: {'name': 'Evan Turner', 'email': 'abbottmichael@gmail.com', 'registered': '1980-02-04', 'timestamp': '12:49:59'}, 149: {'name': 'Jonathan Elliott', 'email': 'jennifermeyer@miranda-davenport.org', 'registered': '1991-06-13', 'timestamp': '13:10:19'}, 150: {'name': 'Kyle Wells', 'email': 'rachel50@yahoo.com', 'registered': '1984-03-10', 'timestamp': '05:28:37'}, 151: {'name': 'Michelle Hammond', 'email': 'brooke28@green.biz', 'registered': '1975-07-16', 'timestamp': '13:13:04'}, 152: {'name': 'Vicki Myers', 'email': 'rachaelreyes@anderson.com', 'registered': '1982-06-10', 'timestamp': '13:43:46'}, 153: {'name': 'Thomas Marshall', 'email': 'zpeterson@hotmail.com', 'registered': '1982-09-03', 'timestamp': '04:15:48'}, 154: {'name': 'Jeffrey Huffman', 'email': 'jonespamela@hotmail.com', 'registered': '1987-07-25', 'timestamp': '12:02:40'}, 155: {'name': 'Mr. Charles Wilson', 'email': 'hillstephanie@wilson.com', 'registered': '1990-02-06', 'timestamp': '18:04:47'}, 156: {'name': 'Dorothy Parks', 'email': 'berrystacy@lewis.com', 'registered': '1977-03-30', 'timestamp': '19:27:24'}, 157: {'name': 'Melissa Erickson', 'email': 'zoeromero@taylor.com', 'registered': '1995-12-26', 'timestamp': '11:32:50'}, 158: {'name': 'Abigail Williams', 'email': 'john03@hayes.com', 'registered': '1994-04-18', 'timestamp': '17:06:53'}, 159: {'name': 'Amy Gonzalez', 'email': 'kristy24@logan.com', 'registered': '2004-03-03', 'timestamp': '20:59:33'}, 160: {'name': 'Ricky Holt', 'email': 'john47@liu.com', 'registered': '1991-02-12', 'timestamp': '18:31:52'}, 161: {'name': 'Andrew Martin', 'email': 'jason33@hotmail.com', 'registered': '1994-09-24', 'timestamp': '10:19:33'}, 162: {'name': 'Joseph Johnson', 'email': 'nmatthews@yahoo.com', 'registered': '2005-05-03', 'timestamp': '15:49:46'}, 163: {'name': 'William Perry', 'email': 'bwest@bullock.com', 'registered': '1997-12-08', 'timestamp': '09:27:39'}, 164: {'name': 'Robert Green', 'email': 'desireewillis@hotmail.com', 'registered': '1987-04-03', 'timestamp': '07:22:57'}, 165: {'name': 'Jason Lee', 'email': 'brian76@yahoo.com', 'registered': '2007-03-12', 'timestamp': '06:35:01'}, 166: {'name': 'Alex Simmons', 'email': 'stewartthomas@hotmail.com', 'registered': '1984-08-28', 'timestamp': '06:28:33'}, 167: {'name': 'Ryan Johnson', 'email': 'morgansheena@espinoza.net', 'registered': '1973-06-12', 'timestamp': '

In [96]:
import os
os.getcwd()

'/Users/linyuli/Desktop/Python'

In [122]:
print(type(main))

<class 'function'>

In [123]:
import pandas as pd
df = pd.read_json('users.json')
df

,1,2,3,4,5,6,7,8,9,10,...,491,492,493,494,495,496,497,498,499,500
name,Donald Cooper,Ryan Howell,Michaela Adams,Jerry Rivera,Emily Manning,Todd Guzman,Joseph Lamb,Mary Martin,Angela Hale,Michelle Thompson,...,Dustin Price,Edward Cruz,Timothy Rivera,William Garcia,Angel Brown,Charles Cox,Pamela Fitzpatrick,James Moore,Christina Bell,Matthew Huffman
email,byrdjeffrey@wright.net,bryanchavez@smith.com,nparker@gmail.com,johnathan39@yahoo.com,annasmith@baker-foster.com,jim25@anderson.biz,tannerhenderson@yahoo.com,kathleen24@austin.com,yhill@vazquez.org,malonejennifer@herrera.org,...,tiffanygillespie@gmail.com,ashley38@hotmail.com,wwood@gmail.com,clairetaylor@garrison-johnson.com,douglasclarke@jones.com,isabella90@hotmail.com,ddavis@yahoo.com,michaelsmith@weber.com,joneswilliam@wolf.info,briancunningham@harris.biz
registered,1990-01-15,2008-01-06,2003-07-01,1976-04-27,1985-08-10,1979-07-23,1984-10-13,1971-06-13,2004-08-28,1978-11-21,...,1979-08-23,2008-01-19,2011-11-01,1976-08-11,1977-07-30,2012-11-13,1986-01-07,2003-01-07,2015-02-05,2015-02-28
timestamp,22:34:17,15:39:05,11:26:07,13:21:36,04:35:15,07:58:39,10:10:08,12:21:38,05:58:00,15:24:52,...,11:35:45,15:15:49,05:27:40,21:14:03,11:33:44,17:28:55,16:37:25,06:35:06,05:24:35,20:12:28

In [150]:
df.transposed = df.T
df.transposed                                   # df_transposed = dfdf.transposed .T # or df.transpose()

                   name                       email  registered timestamp
1         Donald Cooper      byrdjeffrey@wright.net  1990-01-15  22:34:17
2           Ryan Howell       bryanchavez@smith.com  2008-01-06  15:39:05
3        Michaela Adams           nparker@gmail.com  2003-07-01  11:26:07
4          Jerry Rivera       johnathan39@yahoo.com  1976-04-27  13:21:36
5         Emily Manning  annasmith@baker-foster.com  1985-08-10  04:35:15
..                  ...                         ...         ...       ...
496         Charles Cox      isabella90@hotmail.com  2012-11-13  17:28:55
497  Pamela Fitzpatrick            ddavis@yahoo.com  1986-01-07  16:37:25
498         James Moore      michaelsmith@weber.com  2003-01-07  06:35:06
499      Christina Bell      joneswilliam@wolf.info  2015-02-05  05:24:35
500     Matthew Huffman  briancunningham@harris.biz  2015-02-28  20:12:28

[500 rows x 4 columns]

In [159]:
df.transposed['first_record_in_system']= df.transposed['registered'] + " " + df.transposed['timestamp']
df.transposed['first_record_in_system']
output = df.transposed 
output

,name,email,registered,timestamp,first_record_in_system
1,Donald Cooper,byrdjeffrey@wright.net,1990-01-15,22:34:17,1990-01-15 22:34:17
2,Ryan Howell,bryanchavez@smith.com,2008-01-06,15:39:05,2008-01-06 15:39:05
3,Michaela Adams,nparker@gmail.com,2003-07-01,11:26:07,2003-07-01 11:26:07
4,Jerry Rivera,johnathan39@yahoo.com,1976-04-27,13:21:36,1976-04-27 13:21:36
5,Emily Manning,annasmith@baker-foster.com,1985-08-10,04:35:15,1985-08-10 04:35:15
...,...,...,...,...,...
496,Charles Cox,isabella90@hotmail.com,2012-11-13,17:28:55,2012-11-13 17:28:55
497,Pamela Fitzpatrick,ddavis@yahoo.com,1986-01-07,16:37:25,1986-01-07 16:37:25
498,James Moore,michaelsmith@weber.com,2003-01-07,06:35:06,2003-01-07 06:35:06
499,Christina Bell,joneswilliam@wolf.info,2015-02-05,05:24:35,2015-02-05 05:24:35
500,Matthew Huffman,briancunningham@harris.biz,2015-02-28,20:12:28,2015-02-28 20:12:28

In [161]:
output.to_csv('users.csv',header=True)